### ISSUE TITLE
Game Crashes at Alexandra Tower

### ISSUE THREAD

**Issue by Ju99erNutz** [pIayinful/DQ8-Rando#1]
Game Crashes in Tower of Alexandra: Level 1. 

Processor: Arm11 (core 0)
Exception type: data abort
Fault status: Translation - Section
Current process: Honey (000400000018F100)

I'm playing the game on a cfw 2DS Xl. I'm running Luma 10.2.1 and the most recent version of BS9. 

I can include the crash dump if you want. It will just take a while to get it.

Love the randomizer! I'm having a great time!

- Ju99z

**Comment by playinful** [comment]
hi, thanks for the feedback, this could be due to a number of reasons, can you send me the encounter spoiler log and tell me the version of the randomizer you are using? thanks

**Comment by Ju99erNutz** [comment]
I'm running v. 0.3.1 of the rando. Is the spoiler log in the Output/Spoiler folder? 

Thanks

**Comment by playinful** [comment]
Yes, it is.

**Comment by Ju99erNutz** [comment]
[Encounters.txt](https://github.com/pIayinful/DQ8-Rando/files/6469874/Encounters.txt)

**Comment by playinful** [comment]
Thank you. I'll take a look at this and get back to you.

**Comment by Ju99erNutz** [comment]
No problem! Thanks again!

**Comment by playinful** [comment]
Thanks for your inquiry, I've just found it. Turns out it was the One Knight Stand that was causing the issue -- the dictionary entry for it had an incorrect value. This will be fixed in the next release.
